repositories:
  remote:
   - http://repo1.maven.org/maven2

artifacts:
  javax_javaee: javax:javaee-api:jar:7.0
  javax_annotation: com.google.code.findbugs:jsr305:jar:3.0.1

  gwt_user: com.google.gwt:gwt-user:jar:2.8.2
  gwt_dev: com.google.gwt:gwt-dev:jar:2.8.2

  gwt_websockets: org.realityforge.gwt.websockets:gwt-websockets:jar:1.2
